[package]
name = "picture-frame-ui"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"
repository = "https://github.com/dmikusa/digital-picture-frame"

[dependencies]
eframe = "0.32.3"
egui = "0.33.0"
egui_extras = { version = "0.32.3", features = ["all_loaders"] }
image = { version = "0.25.8" }
env_logger = "0.11.8"
retry = "2.1.0"
log = "0.4.28"
anyhow = "1.0.100"
url = "2.5.7"

[dev-dependencies]
tempfile = "3.0"
